/*
 * File: MyViewport.js
 * Date: Wed Aug 29 2012 18:17:47 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyViewport = Ext.extend(MyViewportUi, {
    initComponent: function() {
        MyViewport.superclass.initComponent.call(this);
		
		this.btnCreatabs.on('click',function(){
			var config={
					closable:true,
					xtype : 'gridRegimenesFiscales',
					title : 'Tab 1'
				};
			this.tabPrincipal.add(config).show();
			//this.agregarTab();
			console.log('esto creara tabs');
		},this);
		
		
		
	
	
	
	},

	
});
