/*
 * File: MyViewport.ui.js
 * Date: Wed Aug 29 2012 18:43:28 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    tpl: '',
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'My Panel',
                region: 'center',
                items: [
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        ref: '../tabPrincipal',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Tab 1',
                                tbar: {
                                    xtype: 'toolbar',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'MyButton',
                                            ref: '../../../../btnCreatabs'
                                        }
                                    ]
                                }
                            },
                            {
                                xtype: 'panel',
                                title: 'Tab 2'
                            },
                            {
                                xtype: 'panel',
                                title: 'Tab 3'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'treepanel',
                title: 'My Panel',
                region: 'west',
                width: 116,
                root: {
                    text: 'Tree Node'
                },
                loader: {

                }
            },
            {
                xtype: 'panel',
                title: 'My Panel',
                region: 'north',
                width: 100,
                height: 100
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
