/*
 * File: gridRegimenesFiscales.ui.js
 * Date: Wed Aug 29 2012 20:39:21 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridRegimenesFiscalesUi = Ext.extend(Ext.grid.EditorGridPanel, {
    title: 'Regimenes Fiscales',
    store: '',
    width: 715,
    height: 386,
    initComponent: function() {
        this.bbar = {
            xtype: 'paging',
            store: '',
            ref: 'paginador'
        };
        this.columns = [
            {
                xtype: 'numbercolumn',
                header: 'CodigoRegimen',
                dataIndex: 'CodigoRegimen',
                sortable: true,
                width: 100,
                align: 'right',
                editor: {
                    xtype: 'numberfield'
                }
            },
            {
                xtype: 'gridcolumn',
                header: 'NombreRegimen',
                dataIndex: 'NombreRegimen',
                sortable: true,
                width: 100,
                editor: {
                    xtype: 'textfield'
                }
            },
            {
                xtype: 'gridcolumn',
                header: 'PideCURP',
                dataIndex: 'PideCURP',
                sortable: true,
                width: 100,
                editor: {
                    xtype: 'textfield'
                }
            },
            {
                xtype: 'gridcolumn',
                header: 'Activo',
                dataIndex: 'Activo',
                sortable: true,
                width: 100,
                editor: {
                    xtype: 'textfield'
                }
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    ref: '../btnEliminar'
                }
            ]
        };
        gridRegimenesFiscalesUi.superclass.initComponent.call(this);
    }
});
